- name: Install required software, configure and harden
# ========================================================
  hosts: "{{ cmd_hosts | default('openvpn') }}"

# You need a python interpreter first, so skip gathering facts, then use
# 'setup:' to get them after the python interpreter has been installed.
# See 'pre_tasks' below
  gather_facts: no
  pre_tasks:
    # If python doesn't exist on path (type returns non-zero), install python
    - name: OpenVPN | install | Install python3 if necessary
      raw: 'type python >/dev/null 2>&1 || apt -y install python-minimal'
      changed_when: false

    - name: OpenVPN | install | Gather facts after python3 is available
      setup:

  roles:
    - openvpn